# Generated by Django 3.2 on 2021-04-14 09:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
