# Generated by Django 3.2 on 2021-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_alter_image_model_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_model',
            name='name',
            field=models.CharField(default='ABCD', max_length=250),
        ),
    ]
