# Generated by Django 3.2 on 2021-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_image_model_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fields',
        ),
    ]
