# Generated by Django 3.2 on 2021-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
