# Generated by Django 3.2 on 2021-05-09 14:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_alter_image_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
