# Generated by Django 3.2 on 2021-05-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0006_alter_image_model_location'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image_model',
            managers=[
            ],
        ),
    ]
