# Generated by Django 3.2 on 2021-05-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0008_location_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_model',
            name='location',
        ),
    ]
